apiVersion: v1
kind: Pod
metadata:
  name: build-service-pod
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
        - name: kaniko-kaniko-workspace
          mountPath: /home/jenkins/agent/workspace
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: kaniko-workspace
      persistentVolumeClaim:
        claimName: jenkins-build
